ucdavis/Purchasing

Purchasing.Tests/ServiceTests/SecurityServiceTests.cs
Fixed by not running test. It isn't really very important.
@srkirkland Can you give this a try?
=> Fixes issue where test breaks when in release mode.

Purchasing.Mvc/App_Start/BundleConfig.cs, Purchasing.Mvc/Purchasing.Mvc.csproj, Purchasing.Mvc/Scripts/public/single/jquery.tmpl.js
on
http://prepurchasing-staging.azurewebsites.net/Workgroup/CreateVendor/64
=> Wild guess as to JS error

Purchasing.Mvc/ComponentRegistrar.cs
Commented out so it is easier to switch it back
=> Switch back to ldap. 

Purchasing.Mvc/Views/Report/ProcessingTimeByRole.cshtml, Purchasing.Mvc/Views/Report/ProcessingTimeSummary.cshtml
@srkirkland This still has issues. I'll need some help when you are back in the office.
=> Update help text to reflect the realities of this report

Purchasing.Mvc/Services/NotificationService.cs
There are some that could slip through, but this would catch most of them
=> Don't email users that are inactive.

Purchasing.Mvc/App_Start/LogConfig.cs
@srkirkland Is this better? Looking at stackify, seems we are still getting exceptions
=> Filter by base exception

Purchasing.Mvc/Views/Shared/_Layout.cshtml
Just have the help go to our help ticket site
=> Not UserVoice

Purchasing.Mvc/Purchasing.Mvc.csproj, Purchasing.Mvc/Web.config, Purchasing.Mvc/packages.config, Purchasing.Tests/App.config
Fixes issue with account lookups
=> Update Search, downgrade json

.gitignore, Purchasing.Core/Purchasing.Core.csproj, Purchasing.Core/Services/IndexSearchService.cs, Purchasing.Core/Services/IndexService.cs, Purchasing.Core/app.config, Purchasing.Core/packages.config, Purchasing.Jobs.Common/app.config, Purchasing.Jobs.CreateOrderIndexes/App.config, Purchasing.Jobs.CreateOrderIndexes/Purchasing.Jobs.CreateOrderIndexes.csproj, Purchasing.Jobs.CreateOrderIndexes/packages.config, Purchasing.Jobs.DailyEmailNotifications/App.config, Purchasing.Jobs.EmailNotifications/App.config, Purchasing.Jobs.NightlySync/App.config, Purchasing.Jobs.NotificationsCommon/app.config, Purchasing.Jobs.UpdateLookupIndexes/App.config, Purchasing.Jobs.UpdateLookupIndexes/Purchasing.Jobs.UpdateLookupIndexes.csproj, Purchasing.Jobs.UpdateLookupIndexes/packages.config, Purchasing.Jobs.UpdateOrderIndexes/App.config, Purchasing.Jobs.UpdateOrderIndexes/Purchasing.Jobs.UpdateOrderIndexes.csproj, Purchasing.Jobs.UpdateOrderIndexes/packages.config, Purchasing.Mvc/Controllers/ReportController.cs, Purchasing.Mvc/Purchasing.Mvc.csproj, Purchasing.Mvc/Web.config, Purchasing.Mvc/packages.config, Purchasing.Tests/App.config, Purchasing.Tests/Purchasing.Tests.csproj, Purchasing.Tests/packages.config, Purchasing.WS/app.config
@jSylvestre @jpknoll untested so far, but it compiles at least.  Most of the changes were straightforward but there are a few tricky spots, so please take a look
=> Upgrade to latest ES version

Purchasing.Mvc/Controllers/AdminController.cs, Purchasing.Mvc/Views/Admin/Index.cshtml
and indicate which ones they are
=> Show inactive admins

Purchasing.Mvc/Controllers/ReportController.cs, Purchasing.Mvc/Models/ReportPermissionsViewModel.cs, Purchasing.Mvc/Views/Report/Permissions.cshtml
Toggle to show/hide inherited UsersIssue #329
=> Permissions report enhancements

Purchasing.Mvc/Views/Order/_OrderSaveDialog.cshtml
=> Add warning text to save for later

PurchasingTP.AzureDb/dbo/Functions/udf_GetCommentHistoryForLogin.sql, PurchasingTP.AzureDb/dbo/Functions/udf_GetReadAndEditAccessOrderIdsForLogin.sql, PurchasingTP.AzureDb/dbo/Tables/vAccounts.sql, PurchasingTP.AzureDb/dbo/Tables/vAccounts_sync.sql
Was causing the import to fail.
=> DB change from KFS

Purchasing.Mvc/Helpers/CasHelper.cs
Needed otherwise Stage will probably fail.
=> Use AppSetting for Cas Url

Purchasing.Mvc/Controllers/AdminController.cs, Purchasing.Mvc/Services/IetWsDirectorySearchService.cs
but if there are more than 1, make sure they all have the same kerb id
=> Get the first kerb result,

Purchasing.Mvc/Global.asax.cs
=> Default TLS

Purchasing.Jobs.NotificationsCommon/ProcessNotifications.cs
=> Use like to update -- Email Job

Purchasing.Jobs.NotificationsCommon/ProcessNotifications.cs
=> Put it back.

Purchasing.Mvc/Views/Order/_ReviewOrderDetails.cshtml
(Our Purchaser wanted it for creating KFS vendors from one time vendors)
Also fixed title
=> Display Zip

Purchasing.Mvc/Services/IetWsDirectorySearchService.cs
Moved common calls into method
=> If display name isn't there, return official name

Purchasing.Core/Services/IndexService.cs
=> Limit number of order ids passed

Purchasing.Mvc/Scripts/public/common/startup.js, Purchasing.Mvc/Views/History/Index.cshtml
Moved show tip to table redraw
=> Better binding.

Purchasing.Core/Services/IndexService.cs
=> pump up those numbers

Purchasing.Mvc/Views/Order/_OrderPreferences.cshtml
=> Try to turn off autocomplete

Purchasing.Mvc/Controllers/OrderController.cs
=> Sort it so people with big lists can find them easier

PurchasingTP.AzureDb/dbo/Functions/udf_GetEditAccessRecentOrdersForLogin.sql, PurchasingTP.AzureDb/dbo/Functions/udf_GetOpenOrdersForLogin_New.sql, PurchasingTP.AzureDb/dbo/Functions/udf_GetOpenOrdersForLogin_Old.sql, PurchasingTP.AzureDb/dbo/Functions/udf_GetOrderInformationForUnex.sql, PurchasingTP.AzureDb/dbo/Functions/udf_GetReadAccessRecentOrdersForLogin.sql, PurchasingTP.AzureDb/dbo/Stored Procedures/usp_Update_vSubAccounts_From_vSubAccountsSync.sql, PurchasingTP.AzureDb/dbo/Tables/OrderTracking.sql, PurchasingTP.AzureDb/dbo/Tables/Orders.sql, PurchasingTP.AzureDb/dbo/Views/Get_NEWID.sql, PurchasingTP.AzureDb/dbo/Views/PendingEmails.sql
=> Pulled schema from prod

Purchasing.Mvc/Controllers/UserController.cs, Purchasing.Mvc/Views/User/Profile.cshtml
=> Allow user to update their info from Campus

Purchasing.Jobs.Common/Logging/LogHelper.cs, Purchasing.Mvc/Logging/LogConfig.cs
Not sure if this will cause a conflict with PR #469
=> Monthly logging.

Purchasing.Mvc/Views/History/_OrdersTable.cshtml
=> Hide a span so date sorts

Purchasing.Mvc/Logging/LogConfig.cs, Purchasing.Mvc/Program.cs, Purchasing.Mvc/Purchasing.Mvc.csproj, Purchasing.Mvc/ViewExtensions/HtmlHelperSelectExtensions.cs, Purchasing.Mvc/appsettings.json
I've added the apm settings to purchasing-test, with an enabled setting of false. I haven't added any apm settings to prod.
=> Some final fixes

UCDArch/Web/Attributes/UseTransactionsByDefaultAttribute.cs
The problem was a NRE in UseTransactionsByDefaultAttribute
=> Fix ListSync Authentication

Purchasing.Core/Domain/WorkgroupVendor.cs, Purchasing.Core/Helpers/DateTimeExtensions.cs, Purchasing.Core/Purchasing.Core.csproj, Purchasing.Core/Services/AggieEnterpriseService.cs, Purchasing.Mvc/Controllers/OrderController.cs, Purchasing.Mvc/Controllers/WizardController.cs, Purchasing.Mvc/Controllers/WorkgroupController.cs, Purchasing.Mvc/Controllers/WorkgroupVendorController.cs, Purchasing.Mvc/Services/WorkgroupService.cs, Purchasing.Mvc/Views/Order/_ReviewOrderDetails.cshtml, Purchasing.Mvc/Views/Order/_VendorSearchDialog.cshtml, Purchasing.Mvc/Views/Wizard/AddKfsVendor.cshtml, Purchasing.Mvc/Views/Wizard/Vendors.cshtml, Purchasing.Mvc/Views/Wizard/_VendorTable.cshtml, Purchasing.Mvc/Views/Workgroup/CreateVendor.cshtml, Purchasing.Mvc/Views/Workgroup/VendorList.cshtml, Purchasing.Mvc/Views/Workgroup/_ExistingWorkgroupVendor.cshtml, Purchasing.Tests/ControllerTests/WorkgroupControllerTests/WorkgroupControllerTestsReflection.cs, Purchasing.Tests/RepositoryTests/WorkgroupVendorRepositoryTests.cs, Purchasing.Tests/ServiceTests/WorkgroupServiceTests.cs
Still need to update sever side code as well as wizard and from order.
=> WIP wiring up vendor binding

Purchasing.Core/Models/Configuration/AggieEnterpriseOptions.cs, Purchasing.Core/Services/AggieEnterpriseService.cs
=> For SIT2 Testing. Fake AE CCOA strings for specific accounts

Purchasing.Core/Purchasing.Core.csproj
Note! AE's location code data has changed. Previous values will no longer be correct.
FYI, Mrak room 38 is now `Mrak Hall (350 Mrak Hall Dr)RM 0038, MS21114`
=> New API version

Purchasing.Core/Services/AggieEnterpriseService.cs
Filter out addresses that don't allow delivery and parse the location code to get the building and room
=> AE Location code changes

Purchasing.Mvc/Views/Home/Index.cshtml, Purchasing.Mvc/Views/Order/_ReviewSubmit.cshtml
=> Show warning for Last KFS day

Purchasing.Core/Services/AggieEnterpriseService.cs
=> Better now that I can test

Purchasing.Core/Models/AggieEnterprise/AeJobError.cs, Purchasing.Core/Services/AggieEnterpriseService.cs, Purchasing.Mvc/Controllers/OrderController.cs
When not an array:
{"REQUESTID":1990541,"G_1":{"REQ_IMPORT_ERROR_ID":1,"COLUMN_NAME":"VARIANCE_ACCOUNT_ID","LAST_UPDATE_DATE":"2023-11-15T17:39:59.000+00:00","LAST_UPDATED_BY":"svc.INTEGRATE","INTERFACE_KEY":100000,"LOAD_REQUEST_ID":1990541,"SECTION_ID":"DISTRIBUTION","ERROR_MESSAGE":"The variance account can't be derived. Contact the Procurement application administrator. Oracle Transaction Account Builder can't derive an account. Verify that the account combination is active, allows posting, and segment value security rules restrict none of the segments.","ERROR_CODE":"POR_REQIMP_VACC_NOT_DERIVED","GROUP_ID":17000699518093981}}
When array:
{"REQUESTID":1990796,"G_1":[{"REQ_IMPORT_ERROR_ID":3,"COLUMN_NAME":"VARIANCE_ACCOUNT_ID","LAST_UPDATE_DATE":"2023-11-15T19:00:52.000+00:00","LAST_UPDA …
=> Deal with different formats

Purchasing.Core/Services/AggieEnterpriseService.cs
From Oracle (seems several are optional)
=> more possible nulls

Purchasing.Core/Services/AggieEnterpriseService.cs
Wrap in try catch, upper the passed values
=> Fix KFS Convert

Purchasing.Mvc/Controllers/OrderController.cs
=> Warn about KFS accounts

Purchasing.Mvc/Services/IReportService.cs, Purchasing.Mvc/Views/Order/_ReviewLineItems.cshtml, Purchasing.Mvc/Views/Order/_ReviewLineSplits.cshtml
=> Deal with display of accounting info when no subaccount/project
